config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  get 'welcome/index'
  
  resources :reflections do
    resources :thoughts
  end

  root 'welcome#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/reflection.rb
class Reflection < ApplicationRecord
    has_many :thoughts, dependent: :destroy
    validates :title, presence: true,
                    length: { minimum: 5 }
end

app/models/thought.rb
class Thought < ApplicationRecord
  belongs_to :reflection
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/reflections_controller.rb
class ReflectionsController < ApplicationController

    http_basic_authenticate_with name: "user", password: "secret", except: [:index, :show]

    def index
        @reflections = Reflection.all
    end

    def show
        @reflection = Reflection.find(params[:id])
    end

    def new
        @reflection = Reflection.new
    end

    def edit
        @reflection = Reflection.find(params[:id])
    end

    def create
        @reflection = Reflection.new(reflection_params)

        if @reflection.save
            redirect_to @reflection
        else
            render 'new'
        end
    end

    def update
        @reflection = Reflection.find(params[:id])

        if @reflection.update(reflection_params)
            redirect_to @reflection
        else
            render 'edit'
        end
    end

    def destroy
        @reflection = Reflection.find(params[:id])
        @reflection.destroy

        redirect_to reflections_path
    end

    private

    def reflection_params
        params.require(:reflection).permit(:title, :text)
    end
end

app/controllers/thoughts_controller.rb
class ThoughtsController < ApplicationController
    http_basic_authenticate_with name: "user", password: "secret", only: :destroy

    def create
        @reflection = Reflection.find(params[:reflection_id])
        @thought = @reflection.thoughts.create(thought_params)
        redirect_to reflection_path(@reflection)
      end

    def destroy
    @reflection = Reflection.find(params[:reflection_id])
    @thought = @reflection.thoughts.find(params[:id])
    @thought.destroy
    redirect_to reflection_path(@reflection)
    end  
     
    private

    def thought_params
      params.require(:thought).permit(:thoughter, :body)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/reflections_helper.rb
module ReflectionsHelper
end

app/helpers/thoughts_helper.rb
module ThoughtsHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Reflect</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if notice %>
      <p class="alert alert-success"><%= notice %></p>
    <% end %>
    <% if alert %>
      <p class="alert alert-danger"><%= alert %></p>
    <% end %>
    <%= yield %>
  </body>
</html>

app/views/reflections/_form.html.erb
 <%= form_with model: @reflection, local: true do |form| %>
 
  <% if @reflection.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@reflection.errors.count, "error") %> prohibited
        this reflection from being saved:
      </h2>
      <ul>
        <% @reflection.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
 
  <p>
    <%= form.label :title %><br>
    <%= form.text_field :title %>
  </p>
 
  <p>
    <%= form.label :text %><br>
    <%= form.text_area :text %>
  </p>
 
  <p>
    <%= form.submit %>
  </p>
 
<% end %>

app/views/reflections/edit.html.erb
<h1>Edit reflection</h1>
 
 <%= render 'form' %>
 
<%= link_to 'Back', reflections_path %>

app/views/reflections/index.html.erb
<h1>Listing Articles</h1>
 
<%= link_to 'New Reflection', new_reflection_path %>
<table>
  <tr>
    <th>Title</th>
    <th>Text</th>
    <th colspan="3"></th>
  </tr>
 
  <% @reflections.each do |reflection| %>
    <tr>
      <td><%= reflection.title %></td>
      <td><%= reflection.text %></td>
      <td><%= link_to 'Show', reflection_path(reflection) %></td>
      <td><%= link_to 'Edit', edit_reflection_path(reflection) %></td>
      <td><%= link_to 'Delete', reflection_path(reflection),
              method: :delete,
              data: { confirm: 'Are you sure?' } %></td>
    </tr>
  <% end %>
</table>

app/views/reflections/new.html.erb
<h1>New Reflection</h1>

<%= render 'form' %>

<%= link_to 'Back', reflections_path %>

app/views/reflections/show.html.erb
<p>
  <strong>Title:</strong>
  <%= @reflection.title %>
</p>
 
<p>
  <strong>Text:</strong>
  <%= @reflection.text %>
</p>

<h2>Thoughts:</h2>
<%= render @reflection.thoughts %>

<h2>Add a thought:</h2>
<%= render 'thoughts/form' %>

<%= link_to 'Edit', edit_reflection_path(@reflection) %> |
<%= link_to 'Reflections list', reflections_path %>

app/views/thoughts/_form.html.erb
<%= form_with(model: [ @reflection, @reflection.thoughts.build ], local: true) do |form| %>
  <p>
    <%= form.label :commenter %><br>
    <%= form.text_field :commenter %>
  </p>
  <p>
    <%= form.label :body %><br>
    <%= form.text_area :body %>
  </p>
  <p>
    <%= form.submit %>
  </p>
<% end %>

app/views/thoughts/_thought.html.erb
<p>
  <strong>Commenter:</strong>
  <%= thought.commenter %>
</p>
 
<p>
  <strong>Thought:</strong>
  <%= thought.body %>
</p>

<p>
  <%= link_to 'Delete Thought', [thought.reflection, thought],
               method: :delete,
               data: { confirm: 'Are you sure?' } %>
</p>

app/views/welcome/index.html.erb
<h1>Welcome Rails!</h1>

<%= link_to 'My Reflections', controller: 'reflections' %>